### PR TITLE
Use a ref count rather than worker map for out of sync disconnects

### LINKED ISSUE #290: Cloud erroneously reports VPN connection down
**Describe the bug**
A device may remain in HeartbeatOnly status, but really has a VPN connection with with open-balena-vpn [1]. Look for this sequence of messages in the server VPN logs for the device:

1. Connected to worker X.1
1. Connected to pod Y
1. Quickly disconnected from pod Y
1. Connected to worker X.1 again

There is a silent disconnect from worker X.1 between item 1 and item 4. There likely is a race condition where the disconnect and connect that worker came in the wrong order.

This pattern is distinct from a related sequence where the server logs showed a "dropping oos disconnect" event. See #287 .

[1] At time of writing we have not *confirmed* that the device really has a VPN connection, but it seems likely.

**To Reproduce**
Verify that the device is connected to the VPN if possible.

**Logs / Screenshots**
A number in parentheses at the beginning of a line corresponds to the position in the sequence listed above.

```
17 Aug 2022 12:16:38.893open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=true
17 Aug 2022 12:16:39.038open-balena-vpn-5cf5d597b-djxcq vpn[716]: info: [vpn-127199.1] connection established with client_id=1701769 uuid=3d48dc2ce7eab29b063e38667417afce
17 Aug 2022 12:16:40.942open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=false
(1) 17 Aug 2022 12:16:56.937open-balena-vpn-5cf5d597b-74wz5 vpn[714]: info: [vpn-127211.1] connection established with client_id=1555092 uuid=3d48dc2ce7eab29b063e38667417afce
17 Aug 2022 12:16:57.182open-balena-vpn-5cf5d597b-74wz5 vpn[549]: debug: [vpn-127211] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=true
17 Aug 2022 12:38:49.398open-balena-vpn-5cf5d597b-djxcq vpn[716]: info: [vpn-127199.1] connection established with client_id=1724529 uuid=3d48dc2ce7eab29b063e38667417afce
(2) 17 Aug 2022 12:38:50.022open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=true
(3) 17 Aug 2022 12:38:54.141open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=false
(4) 17 Aug 2022 12:39:08.755open-balena-vpn-5cf5d597b-74wz5 vpn[714]: info: [vpn-127211.1] connection established with client_id=1577933 uuid=3d48dc2ce7eab29b063e38667417afce
17 Aug 2022 13:01:36.929open-balena-vpn-5cf5d597b-74wz5 vpn[714]: info: [vpn-127211.1] connection established with client_id=1600626 uuid=3d48dc2ce7eab29b063e38667417afce
`

### PR DESCRIPTION
**Pull request by Page-**
Fixes #290

### CODE REVIEW

File: src/api.ts [hunk 1]
```diff
@@ -81,16 +81,16 @@ export const apiFactory = (serviceId: number) => {
 		// Immediately respond to minimize time in the client-connect script
 		res.status(200).end();
 
-		metrics.inc(Metrics.OnlineDevices);
+		if (clientRefCount[uuid] === 0) {
+			// Only increment the device as online if it wasn't previously online
+			metrics.inc(Metrics.OnlineDevices);
+		}
 		metrics.inc(Metrics.TotalDevices);
+		clientRefCount[uuid]++;
```
Comment (Page-) [inline src/api.ts:89]: This needs to be initialized btw for anyone looking, I've just pushed up this version because I'm hitting a typescript crash with it for some reason :S

Comment (Page-) [reply src/api.ts:89]: The crash is related to `uuid` being defined below but used here

Comment (Page-) [reply src/api.ts:89]: https://github.com/microsoft/TypeScript/issues/50591

**Review by thgreasi — COMMENTED** [review]
LGTM from what I can get :+1:

**Review by thgreasi — APPROVED** [review]
